# Brewfile — install with: `brew bundle --file=Brewfile`
# Generated from `brew leaves` and `brew list --cask` on my MacBook Pro.

# --- Taps --------------------------------------------------------------------
tap "bufbuild/buf"
tap "carvel-dev/carvel"
tap "databricks/tap"
tap "homebrew/bundle"
tap "int128/kubelogin"

# --- CLI tools (formulae) ----------------------------------------------------
brew "actionlint"
brew "awscli"
brew "bash"
brew "bat"
brew "bufbuild/buf/buf"
brew "carvel-dev/carvel/kapp"
brew "databricks/tap/databricks"
brew "eksctl"
brew "gh"
brew "go"
brew "gron"
brew "helm"
brew "int128/kubelogin/kubelogin"
brew "jenv"
brew "jq"
brew "kind"
brew "kubectx"
brew "kubernetes-cli@1.29"
brew "kustomize"
brew "librsvg"
brew "postgresql@14"
brew "pyenv"
brew "regclient"
brew "ripgrep"
brew "stern"
brew "terraform"
brew "terragrunt"
brew "tfenv"
brew "tilt"
brew "trivy"
brew "yq"
brew "z"

# --- GUI apps (casks) --------------------------------------------------------
cask "1password"
cask "1password-cli"
cask "iterm2"
cask "rectangle"
cask "tableplus"
cask "visual-studio-code"
